### ISSUE TITLE
Multiple doc locations

### ISSUE THREAD

**Issue by beardedeagle** [amonapp/amon-docs#2]
There appears to be docs at `docs.amon.cx` and `amon.cx/docs`, with `docs.amon.cx` being more current. In the interest of not confusing an enduser, is there a plan to retire the older docs?

**Comment by martinrusev** [comment]
@beardedeagle Can you show me the location where I still link the old documentation?

**Comment by beardedeagle** [comment]
@martinrusev:
- From the main page, all links under `Plays well with others`
- From the main page, under `Nagios & Sensu compatible`
- From the main page, under `Easy StatsD`
- Several links on the `tour/` page (Not sure if this is a seperate page than `tour/server-monitoring/`)
- Several links on the `tour/server-monitoring/` page
- On the `tour/integrations/pagerduty/` page
- On the `tour/integrations/python/` page
- On the `tour/integrations/ruby/` page
- On the `tour/integrations/php/` page
- On the `tour/integrations/nodejs/` page
- On the `tour/integrations/elastic/` page
- On the `tour/integrations/memcached/` page
- On the `tour/integrations/statsd/` page
- On the `tour/integrations/rabbitmq/` page
- On the `tour/integrations/haproxy/` page
- On the `tour/integrations/rethinkdb/` page
- On the `tour/integrations/custom/` page
- On the `tour/integrations/pagerduty/` page
- On the `guides/alerts/` page

I didn't look at anything in `/blog` at all.

**Comment by martinrusev** [comment]
@beardedeagle Fixed. Thanks
